### ISSUE TITLE
How to share symbols

### ISSUE THREAD

**Issue by bstroebl** [qgis/QGIS-Resources#3]
I have created a bunch of svg symbols, mainly interesting for a German audience as it implements the German _Planzeichenverordnung_. They are currently available [here](http://qgis.de/download/planzv.zip).
I could either upload them on a separate github repo 
- any rules on directories etc.?
- how can I have this repo included in the _offical repositories_?

or make a PR against this repo. Which would you prefer?

**Comment by elpaso** [comment]
Have a look to the new sharing plugin: http://www.akbargumbira.com/qgis_resources_sharing/

**Comment by elpaso** [comment]
Yes: a PR against this would be the preferred way

**Comment by bstroebl** [comment]
> Have a look to the new sharing plugin: http://www.akbargumbira.com/qgis_resources_sharing/

sorry, I didn't realize the menu on the left. Will read and then call again.

**Comment by akbargumbira** [comment]
@bstroebl let us know if you have problem (sorry just settle in again)

**Comment by bstroebl** [comment]
@akbargumbira thanks for reminding me, it slipped out of my focus, repository for my resources has been set up, PR is pending
